version: '3.8'
services:
  db:
    image: postgres:16
    container_name: cross-platform-starter-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-appdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
